apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-tmc-catalog
  name: cert-manager-tmc-catalog-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-tmc-catalog-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-manager-tmc-catalog-sa
  namespace: tmc-catalog
