# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: letsencrypt-http01-clusterissuer
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   path: ../../../config/cert-manager/letsencrypt-http01-clusterissuer-certificates.yaml
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: artoftanzu-fleetinfra
#   postBuild:
#     substitute:
#       service_fqdn: tap-gui.wc1-useast2-aws.tanzu.art
#       service_vanity_fqdn: tap-gui.tanzu.art
