---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: letsencrypt-http01-clusterissuer
  namespace: flux-system
spec:
  interval: 10m0s
  path: ../../../config/cert-manager/letsencrypt-http01-clusterissuer.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: artoftanzu-fleetinfra