apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: afewell@gmail.com
    privateKeySecretRef:
      name: letsencrypt-http01-clusterissuer
    solvers:
    - http01:
        ingress:
          class: contour