apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: tap-gui
spec:
  commonName: ${service_fqdn}
  dnsNames:
    - ${service_fqdn}
    - ${service_vanity_fqdn}
  issuerRef:
    name: letsencrypt-http01-clusterissuer
    kind: ClusterIssuer
  secretName: tap-gui